name: maxopen_flutter_junior
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  go_router: ^14.2.0
  intl: ^0.19.0
  sliding_clipped_nav_bar: ^3.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  generate: true

  assets:
    - /Users/igorgrebenyuk/Documents/proj/Maxopen_flutter_junior/maxopen_flutter_junior/assets/icons/
    
  uses-material-design: true

  fonts:
    - family: Poppins-Bold
      fonts:
        - asset: /Users/igorgrebenyuk/Documents/proj/Maxopen_flutter_junior/maxopen_flutter_junior/assets/fonts/Poppins-Bold.ttf
          weight: 700